"""Materialize the non-secret, project-local Tsunagou onboarding contract."""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tsunagou.modules.projects import ProjectRegistry
from tsunagou.platform.db.sqlite import ProjectLock
from tsunagou.shared_kernel.digests import canonical_digest

SOURCE_REPOSITORY = "https://github.com/tyuikl32/Tsunagou.git"
GENERATOR_VERSION = "project-bootstrap-v1"
START_MARKER = "<!-- TSUNAGOU:START -->"
END_MARKER = "<!-- TSUNAGOU:END -->"


class ProjectIntegrationError(RuntimeError):
    """A project-local integration cannot be safely materialized."""


@dataclass(frozen=True, slots=True)
class _ManagedFile:
    path: Path
    content: str


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _read(path: Path) -> str | None:
    if not path.exists():
        return None
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeError as exc:
        raise ProjectIntegrationError(f"managed_file_not_utf8:{path}") from exc


def _replace_block(existing: str | None, block: str, *, path: Path) -> tuple[str, str]:
    if existing is None:
        return block, "created"
    start = existing.find(START_MARKER)
    end = existing.find(END_MARKER)
    if start == -1 and end == -1:
        separator = "" if existing.endswith(("\n", "\r")) else "\n"
        return existing + separator + "\n" + block, "updated"
    if start == -1 or end < start:
        raise ProjectIntegrationError(f"managed_marker_conflict:{path}")
    end += len(END_MARKER)
    replacement = existing[:start] + block + existing[end:]
    return replacement, "unchanged" if replacement == existing else "updated"


def _git_commit(source_root: Path | None) -> str | None:
    if source_root is None or not (source_root / ".git").exists():
        return None
    try:
        completed = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "HEAD"],
            capture_output=True, check=False, text=True, timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    value = completed.stdout.strip()
    return value if completed.returncode == 0 and value else None


def _source_metadata(source_root: Path | None, source_ref: str | None) -> dict[str, Any]:
    resolved = source_root.expanduser().resolve() if source_root else None
    return {
        "repository": SOURCE_REPOSITORY,
        "ref": source_ref or "working-tree",
        "commit": _git_commit(resolved),
        "install_path_hint": str(resolved) if resolved else None,
    }


def _render_context(project_id: str, source: dict[str, Any], source_root: Path | None) -> str:
    source_hint = source.get("install_path_hint") or "未提供本机 checkout 路径；使用 GitHub source 和项目相对规范链接"
    local_docs = str(source_root / "docs") if source_root else "<Tsunagou checkout>/docs"
    return f"""# Tsunagou 项目上下文

<!-- Generated by {GENERATOR_VERSION}. Do not edit the generated sections directly. -->

## 项目标识

- `project_id`: `{project_id}`
- daemon: 本机 Tsunagou daemon；项目入口不创建全局单例，当前项目始终由 `project_id` 区分。
  一个安装 checkout 可服务多个项目；daemon 是否启用多项目运行由实际 runtime/doctor 结果证明。
- Tsunagou source: {source['repository']}（ref `{source['ref']}`，commit `{source.get('commit') or 'unknown'}`）
- 本机 source path 仅为诊断提示：`{source_hint}`

## Agent 工作边界

1. 第一次行动前先读取本文件、当前 Agent/session 身份、黑板和收件箱；不能凭旧对话猜测任务或权限。
2. 主 Agent 负责任务统筹、Git 写操作、整合和需要用户确认的重大决定。
   子 Agent 只能使用自己领取的 Attempt，不能任命自己为 main、接管主任务或代用户确认。
3. `claim` 只领取任务，`preflight` 只准备，`start` 才获得当前 scope 的执行授权。
   Full Access 宿主不等于获得 Tsunagou scope，也不等于 OS 沙箱。
4. 认知报告、契约接受、消息 ACK、Task 完成和 Project 完成是不同事实；ACK 不表示同意，项目完成必须由用户确认。
5. 上游决定阻塞时保存进展并结束本轮；不相交的任务可以继续。恢复前重新读取状态，不复用过期 Grant、Lease 或旧 session 假设。
6. 需要扩大范围、改变项目设计或处理无法协调的冲突时向主 Agent 提出；越过用户上限时建立 UserDecision，不能自行绕过。

## 接入入口

- 安装/恢复向导：`tsunagou-agent-onboarding` skill。
- 当前项目轻量入口：`.agents/skills/tsunagou-project/SKILL.md`。
- 规范源码（本机可用时）：`{local_docs}/overview/agent-quick-start.md`、`{local_docs}/overview/subagent-guide.md`。
  任务和身份规范：`{local_docs}/implementation/modules/02-agents.md`、`{local_docs}/implementation/modules/03-tasks.md`。
- 在线来源：`{source['repository']}`；项目入口不复制 Tsunagou 源码。

## 运行数据边界

`.tsunagou/project-integration.json` 和本文件是无秘密的项目共享入口。
`.tsunagou/local/`、endpoint、control token、ticket、bridge session、SQLite 和日志是本机私有数据，不能提交、粘贴给 Agent 或复制到别的对话。
"""


def _render_skill() -> str:
    return f"""---
name: tsunagou-project
description: "Project-local Tsunagou coordination entry. Read the project context before using the bridge or changing files."
---

# Tsunagou Project Entry

This is a small project-local wrapper. It does not replace the Tsunagou daemon,
bridge, or onboarding skill and it grants no permission.

1. Read `.tsunagou/agent-context.md` and the managed Tsunagou block in `AGENTS.md`.
2. Ask the bridge for the current project/Agent/session context; `ticket_issued` is not ready.
3. Read the incremental inbox and blackboard before acting. A worker waits for a published task and claims only its own Attempt.
4. Follow the main/worker/user boundaries, Full Access limitation, Git ownership, and recovery rules in the context file.
5. For installation or enrollment, follow `tsunagou-agent-onboarding`; never request or print tokens.

Generated by `{GENERATOR_VERSION}`. Refresh through `tsunagou project bootstrap --refresh`.
"""


def _render_agents_block() -> str:
    return f"""{START_MARKER}
## Tsunagou project rules

Before changing files, read `.tsunagou/agent-context.md` and the current Agent/session context.
The daemon and bridge enforce identity, task owner, scope, revision and epoch; this file is a project instruction, not an OS sandbox.
The main Agent coordinates tasks and performs Git writes. A worker cannot become main or act outside its own claimed Attempt.
`claim`/`preflight`/`start` are separate; Full Access does not expand Tsunagou scope.
Major design, permission and project-completion decisions remain user-controlled.
Use `tsunagou-agent-onboarding` for enrollment and recovery. Do not put tokens, tickets or bridge sessions in prompts or commits.

Generated by `{GENERATOR_VERSION}`. Source and detailed rules: `.tsunagou/agent-context.md`.
{END_MARKER}"""


def _render_gitignore_block() -> str:
    return f"""{START_MARKER}
# Tsunagou local runtime and credentials
.tsunagou/local/
.tsunagou/bridges/
.tsunagou/**/*.token
.tsunagou/**/*.sqlite3
.tsunagou/**/*.log
{END_MARKER}"""


class ProjectIntegration:
    """Generate and update project-local onboarding files."""

    def __init__(self, coordination_root: str | Path) -> None:
        self.root = Path(coordination_root).expanduser().resolve()
        self.state_dir = self.root / ".tsunagou"

    def bootstrap(
        self,
        *,
        source_root: str | Path | None = None,
        source_ref: str | None = None,
        hosts: list[str] | None = None,
        refresh: bool = False,
        force_managed: bool = False,
    ) -> dict[str, Any]:
        lock_name = canonical_digest({"coordination_root": str(self.root)}) + ".lock"
        lock_path = Path(tempfile.gettempdir()) / "tsunagou-project-locks" / lock_name
        with ProjectLock(lock_path):
            return self._bootstrap_locked(
                source_root=source_root,
                source_ref=source_ref,
                hosts=hosts,
                refresh=refresh,
                force_managed=force_managed,
            )

    def _bootstrap_locked(
        self,
        *,
        source_root: str | Path | None,
        source_ref: str | None,
        hosts: list[str] | None,
        refresh: bool,
        force_managed: bool,
    ) -> dict[str, Any]:
        registry = ProjectRegistry(self.root)
        if registry.project is None:
            raise ProjectIntegrationError("project_not_initialized")
        if not registry.is_git_repository():
            raise ProjectIntegrationError("coordination_repository_must_be_git_repository")
        source_path = Path(source_root).expanduser().resolve() if source_root else None
        source = _source_metadata(source_path, source_ref)
        context = _render_context(registry.project.project_id, source, source_path)
        skill = _render_skill()
        agents_block = _render_agents_block()
        gitignore_block = _render_gitignore_block()
        content_digest = canonical_digest({
            "context": context, "skill": skill,
            "agents_block": agents_block, "gitignore_block": gitignore_block,
        })
        manifest = {
            "schema_version": 1,
            "project_id": registry.project.project_id,
            "project_root_id": registry.project.coordination_repository_id,
            "source": source,
            "generated_by": GENERATOR_VERSION,
            "managed_files": [
                "AGENTS.md#TSUNAGOU", ".agents/skills/tsunagou-project/SKILL.md",
                ".tsunagou/agent-context.md", ".tsunagou/project-integration.json",
                ".gitignore#TSUNAGOU",
            ],
            "content_digest": content_digest,
            "updated_at": content_digest,
        }
        managed = [
            _ManagedFile(
                self.state_dir / "project-integration.json",
                json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
            ),
            _ManagedFile(self.state_dir / "agent-context.md", context),
            _ManagedFile(self.root / ".agents" / "skills" / "tsunagou-project" / "SKILL.md", skill),
        ]
        planned: list[tuple[Path, str, str]] = [
            self._plan_exact(item, refresh=refresh, force_managed=force_managed)
            for item in managed
        ]
        planned.append(
            self._plan_block(self.root / "AGENTS.md", agents_block, refresh=refresh, force_managed=force_managed)
        )
        planned.append(
            self._plan_block(self.root / ".gitignore", gitignore_block, refresh=refresh, force_managed=force_managed)
        )
        # All conflict checks happen before the first replacement. A user-file
        # conflict therefore cannot leave a partially materialized project.
        statuses: list[dict[str, str]] = []
        for path, content, status in planned:
            if status != "unchanged":
                _atomic_text(path, content)
            statuses.append({"path": str(path.relative_to(self.root)), "status": status})
        return {
            "status": "bootstrapped", "project_id": registry.project.project_id,
            "coordination_root": str(self.root), "source": source,
            "hosts": hosts or ["generic"], "content_digest": content_digest,
            "files": statuses, "secrets_written": False,
        }

    def _plan_exact(self, item: _ManagedFile, *, refresh: bool, force_managed: bool) -> tuple[Path, str, str]:
        existing = _read(item.path)
        if existing is None:
            return item.path, item.content, "created"
        if existing == item.content:
            return item.path, existing, "unchanged"
        if not (refresh or force_managed) or GENERATOR_VERSION not in existing:
            raise ProjectIntegrationError(f"managed_file_conflict:{item.path}")
        return item.path, item.content, "updated"

    def _plan_block(self, path: Path, block: str, *, refresh: bool, force_managed: bool) -> tuple[Path, str, str]:
        existing = _read(path)
        if existing is not None and START_MARKER in existing and END_MARKER in existing:
            start = existing.find(START_MARKER)
            end = existing.find(END_MARKER, start)
            if end < start:
                raise ProjectIntegrationError(f"managed_marker_conflict:{path}")
            current = existing[start : end + len(END_MARKER)]
            if current != block and not (refresh or force_managed):
                raise ProjectIntegrationError(f"managed_file_conflict:{path}")
        updated, status = _replace_block(existing, block, path=path)
        return path, updated, status
