"""Materialize the non-secret, project-local Tsunagou onboarding contract."""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tsunagou.modules.projects import ProjectRegistry
from tsunagou.platform.db.sqlite import ProjectLock
from tsunagou.platform.runtime_context import read_object, running_source_root
from tsunagou.shared_kernel.digests import canonical_digest
from tsunagou.shared_kernel.time import format_timestamp, now_ms, parse_timestamp

SOURCE_REPOSITORY = "https://github.com/tyuikl32/Tsunagou.git"
GENERATOR_VERSION = "project-bootstrap-v4"
START_MARKER = "<!-- TSUNAGOU:START -->"
END_MARKER = "<!-- TSUNAGOU:END -->"


class ProjectIntegrationError(RuntimeError):
    """A project-local integration cannot be safely materialized."""


@dataclass(frozen=True, slots=True)
class _ManagedFile:
    path: Path
    content: str


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _read(path: Path) -> str | None:
    if not path.exists():
        return None
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeError as exc:
        raise ProjectIntegrationError(f"managed_file_not_utf8:{path}") from exc


def _replace_block(
    existing: str | None, block: str, *, path: Path,
    start_marker: str = START_MARKER, end_marker: str = END_MARKER,
) -> tuple[str, str]:
    if existing is None:
        return block, "created"
    start = existing.find(start_marker)
    end = existing.find(end_marker)
    if start == -1 and end == -1:
        separator = "" if existing.endswith(("\n", "\r")) else "\n"
        return existing + separator + "\n" + block, "updated"
    if start == -1 or end < start:
        raise ProjectIntegrationError(f"managed_marker_conflict:{path}")
    end += len(end_marker)
    replacement = existing[:start] + block + existing[end:]
    return replacement, "unchanged" if replacement == existing else "updated"


def _git_commit(source_root: Path | None) -> str | None:
    if source_root is None or not (source_root / ".git").exists():
        return None
    try:
        completed = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "HEAD"],
            capture_output=True, check=False, text=True, timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    value = completed.stdout.strip()
    return value if completed.returncode == 0 and value else None


def _source_metadata(source_root: Path | None, source_ref: str | None) -> dict[str, Any]:
    resolved = source_root.expanduser().resolve() if source_root else None
    return {
        "repository": SOURCE_REPOSITORY,
        "ref": source_ref or "working-tree",
        "commit": _git_commit(resolved),
        "install_path_hint": str(resolved) if resolved else None,
    }


def _render_context(project_id: str, source: dict[str, Any], source_root: Path | None) -> str:
    source_hint = source.get("install_path_hint") or "未提供本机 checkout 路径；使用 GitHub source 和项目相对规范链接"
    local_docs = str(source_root / "docs") if source_root else "<Tsunagou checkout>/docs"
    return f"""# Tsunagou 项目上下文

<!-- Generated by {GENERATOR_VERSION}. Do not edit the generated sections directly. -->

## 项目标识

- `project_id`: `{project_id}`
- daemon: 本机 Tsunagou daemon；项目入口不创建全局单例，当前项目始终由 `project_id` 区分。
  一个安装 checkout 可服务多个项目；daemon 是否启用多项目运行由实际 runtime/doctor 结果证明。
- Tsunagou source: {source['repository']}（ref `{source['ref']}`，commit `{source.get('commit') or 'unknown'}`）
- 本机 source path 仅为诊断提示：`{source_hint}`

## Agent 工作边界

1. 第一次行动前先读取本文件、当前 Agent/session 身份、黑板和收件箱；之后每轮开始和每个自然断点
   （子步骤完成、构建或测试跑完）再读一次，不能凭旧对话猜测任务或权限。
2. 主 Agent 负责任务统筹、Git 写操作、整合和需要用户确认的重大决定。
   子 Agent 只能使用自己领取的 Attempt，不能任命自己为 main、接管主任务或代用户确认。
   main 收到子 Agent 请求后，检查现有任务及重复请求，再自主发布合适任务、明确回复无需新任务，或说明实际阻塞。
   普通调度沿已有用户授权执行，不再次询问“是否需要发布任务”；必须履行回复义务，不能只读消息或 ACK。
   但“新增一个 Agent”不是普通调度：让一个新会话（新身份）加入本项目必须由用户明确允许；
   在那之前主 Agent 不得自行签发接入票据、邀请或组织新会话加入，也不要替用户决定该用哪个宿主。
   觉得人手不够时，向用户说明理由并请求允许，等用户点头再接入。
3. 项目目标不是建项目时填好的：项目记录里那句只是占位（“待主 Agent 与用户确认”）。
   主 Agent 与用户把目标谈清楚后，用 `user_decision.propose` 提一条决定（`kind=project.objective`、
   `summary` 写目标本身、`choices` 给出可选答复）；用户确认后那句才是项目目标，界面也才显示它。
   在那之前不要把占位句当目标复述，也不要替用户宣称目标已经确定。
4. 读取任务的当前 revision 后调用 `task.begin`，成功才获得当前 scope 的执行授权；`task.submit` 自动收集结果并释放占用。文件任务的执行范围由主 Agent 在发布前写进 `execution_scope`；两个任务会碰同一批文件时，先谈妥一条契约再开工 —— 不声明范围不等于不会撞。
   Full Access 宿主不等于获得 Tsunagou scope，也不等于 OS 沙箱。
5. 认知报告、契约接受、消息 ACK、Task 完成和 Project 完成是不同事实；ACK 不表示同意，项目完成必须由用户确认。
6. 上游决定阻塞时调用 `task.block` 保存进展、释放占用并结束本轮；不相交的任务可以继续。
   恢复前重读状态并再次 begin。静默、断线或同库重启不会转移资源 owner，主 Agent 可以显式回收。
7. 需要扩大范围、改变项目设计或处理无法协调的冲突时向主 Agent 提出；越过用户上限时建立 UserDecision，不能自行绕过。

## 被拒时怎么办

工具调用失败会以错误返回，形如 `{{"error": "tsunagou_error:<错误码>", "code": "...", "next_steps": [...]}}`。
**先看错误里给出的 `next_steps` 与清单，按它做，再重试** —— 不要换一种说法反复硬试，也不要自己构造或粘贴凭据。

## 接入入口

- 安装/恢复向导：`tsunagou-agent-onboarding` skill。
- 当前项目轻量入口：`.agents/skills/tsunagou-project/SKILL.md`。
- 规范源码（本机可用时）：`{local_docs}/overview/agent-quick-start.md`、`{local_docs}/overview/subagent-guide.md`。
  任务和身份规范：`{local_docs}/implementation/modules/02-agents.md`、`{local_docs}/implementation/modules/03-tasks.md`。
- 在线来源：`{source['repository']}`；项目入口不复制 Tsunagou 源码。

## 运行数据边界

`.tsunagou/project-integration.json` 和本文件是无秘密的项目共享入口。
`.tsunagou/local/`、endpoint、control token、ticket、bridge session、SQLite 和日志是本机私有数据，不能提交、粘贴给 Agent 或复制到别的对话。
"""


def _render_skill() -> str:
    return f"""---
name: tsunagou-project
description: "Project-local Tsunagou coordination entry. Read the project context before using the bridge or changing files."
---

# Tsunagou Project Entry

This is a small project-local wrapper. It does not replace the Tsunagou daemon,
bridge, or onboarding skill and it grants no permission.

1. Read `.tsunagou/agent-context.md` and the managed Tsunagou block in `AGENTS.md`.
2. Ask the bridge for the current project/Agent/session context; `ticket_issued` is not ready.
3. Read the incremental inbox and blackboard on each turn and at every natural break (a finished sub-step,
   a build or a test run). A worker calls task.begin on eligible published work and uses the returned Attempt.
   A file task's execution_scope is main's decision and is written before publication; when two tasks would touch the same files, main settles a contract first.
   Main handles routine worker requests under existing authorization: check duplicates, publish work or reply with a concrete reason.
   Reading or ACK alone is not a response.
4. Follow the main/worker/user boundaries, Full Access limitation, Git ownership, and recovery rules in the context file.
   Adding a **new** Agent to the project is the user's decision, not ordinary scheduling;
   work for the Agents already here still needs no new authorization.
5. For installation or enrollment, follow `tsunagou-agent-onboarding`; never request or print tokens.

Generated by `{GENERATOR_VERSION}`. Refresh through `tsunagou project bootstrap --refresh`.
"""


def _render_agents_block() -> str:
    return f"""{START_MARKER}
## Tsunagou project rules

Before changing files, read `.tsunagou/agent-context.md` and the current Agent/session context.
The daemon and bridge enforce identity, task owner, scope, revision and epoch; this file is a project instruction, not an OS sandbox.
The main Agent coordinates tasks and performs Git writes. A worker cannot become main or act outside its own claimed Attempt.
The main Agent proactively handles routine worker requests: check existing work, publish or reply, and fulfill response obligations.
Do not ask the user to authorize ordinary scheduling again.
Enrolling a **new** Agent (a new host conversation joining this project) is not ordinary scheduling: the user decides it.
Do not invite, ticket or enroll one on your own initiative; ask the user first, and let them choose the host.
`task.begin` prepares and starts the owned attempt; `task.submit` captures results and releases it. Main writes a file task's `execution_scope` before publishing it, and when two tasks would touch the same files it settles a contract first: an unstated scope is not a protected one.
Full Access does not expand Tsunagou scope.
The project goal is agreed with the user, not filled in when the project is created: the `objective` field holds a
placeholder until the main Agent proposes `user_decision.propose` with `kind=project.objective` and the user confirms it.
Do not quote the placeholder as if it were the goal, and do not claim a goal the user has not confirmed.
Major design, permission and project-completion decisions remain user-controlled.
Use `tsunagou-agent-onboarding` for enrollment and recovery. Do not put tokens, tickets or bridge sessions in prompts or commits.

Generated by `{GENERATOR_VERSION}`. Source and detailed rules: `.tsunagou/agent-context.md`.
{END_MARKER}"""


def _render_gitignore_block() -> str:
    return f"""{START_MARKER}
# Tsunagou local runtime and credentials
.tsunagou/local/
.tsunagou/bridges/
.tsunagou/**/*.token
.tsunagou/**/*.sqlite3
.tsunagou/**/*.log
# The MCP entry OpenCode is configured with lands at the project root.
/opencode.json
{END_MARKER}"""


class ProjectIntegration:
    """Generate and update project-local onboarding files."""

    def __init__(self, coordination_root: str | Path) -> None:
        self.root = Path(coordination_root).expanduser().resolve()
        self.state_dir = self.root / ".tsunagou"

    def bootstrap(
        self,
        *,
        source_root: str | Path | None = None,
        source_ref: str | None = None,
        hosts: list[str] | None = None,
        refresh: bool = False,
        force_managed: bool = False,
    ) -> dict[str, Any]:
        # ``canonical_digest`` is a protocol/display digest (``sha256:<hex>``).
        # A colon is not a legal character in Windows filenames, so preserve the
        # algorithm marker with a filename-safe separator while retaining the
        # complete digest for stable per-root lock isolation.
        lock_name = canonical_digest({"coordination_root": str(self.root)}).replace(":", "-", 1) + ".lock"
        lock_path = Path(tempfile.gettempdir()) / "tsunagou-project-locks" / lock_name
        with ProjectLock(lock_path):
            return self._bootstrap_locked(
                source_root=source_root,
                source_ref=source_ref,
                hosts=hosts,
                refresh=refresh,
                force_managed=force_managed,
            )

    def _bootstrap_locked(
        self,
        *,
        source_root: str | Path | None,
        source_ref: str | None,
        hosts: list[str] | None,
        refresh: bool,
        force_managed: bool,
    ) -> dict[str, Any]:
        registry = ProjectRegistry(self.root)
        if registry.project is None:
            raise ProjectIntegrationError("project_not_initialized")
        if not registry.is_git_repository():
            raise ProjectIntegrationError("coordination_repository_must_be_git_repository")
        selected_hosts = sorted(set(hosts or ["generic"]))
        if set(selected_hosts) - {"generic", "codex", "claude", "cursor", "opencode", "gemini", "zcode", "deepseek"}:
            raise ProjectIntegrationError("unsupported_skill_host")
        source_path = Path(source_root).expanduser().resolve() if source_root else running_source_root()
        source = _source_metadata(source_path, source_ref)
        context = _render_context(registry.project.project_id, source, source_path)
        skill = _render_skill()
        agents_block = _render_agents_block()
        gitignore_block = _render_gitignore_block()
        host_files = [
            _ManagedFile(self.root / f".{host}/skills/tsunagou-project/SKILL.md", skill)
            # DeepSeek Harness discovers project skills at `<projectRoot>/.agents/skills`
            # with no vendor-specific root, so it needs no extra copy of the same file.
            for host in selected_hosts if host not in {"generic", "codex", "deepseek"}
        ]
        host_config: str | None = None
        if "codex" in selected_hosts:
            from tsunagou.application.onboarding import codex_routing_directory

            if source_path is None or not (source_path / "packages/bridge-server/dist/server.js").is_file():
                raise ProjectIntegrationError("installation_bridge_not_built")
            host_config = (
                '# TSUNAGOU:START\n[mcp_servers.tsunagou]\ncommand = "node"\n'
                f'args = {json.dumps([str(source_path / "packages/bridge-server/dist/server.js")])}\n'
                'env_vars = ["CODEX_APP_TOOLS_PIPE_PATH"]\n'
                '[mcp_servers.tsunagou.env]\n'
                f'TSUNAGOU_ROUTING_DIR = {json.dumps(str(codex_routing_directory()))}\n# TSUNAGOU:END'
            )
        content_digest = canonical_digest({
            "context": context, "skill": skill,
            "agents_block": agents_block, "gitignore_block": gitignore_block,
            "hosts": selected_hosts, "host_config": host_config,
        })
        previous = read_object(self.state_dir / "project-integration.json")
        updated_at = previous.get("updated_at") if previous.get("content_digest") == content_digest else None
        try:
            parse_timestamp(updated_at)
        except ValueError:
            updated_at = None
        manifest = {
            "schema_version": 1,
            "project_id": registry.project.project_id,
            "project_root_id": registry.project.coordination_repository_id,
            "source": source,
            "generated_by": GENERATOR_VERSION,
            "managed_files": [
                "AGENTS.md#TSUNAGOU", ".agents/skills/tsunagou-project/SKILL.md",
                ".tsunagou/agent-context.md", ".tsunagou/project-integration.json",
                ".gitignore#TSUNAGOU",
            ] + [str(item.path.relative_to(self.root)).replace("\\", "/") for item in host_files]
              + ([".codex/config.toml#TSUNAGOU"] if host_config else []),
            "content_digest": content_digest,
            "updated_at": updated_at or format_timestamp(now_ms()),
        }
        managed = [
            _ManagedFile(
                self.state_dir / "project-integration.json",
                json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
            ),
            _ManagedFile(self.state_dir / "agent-context.md", context),
            _ManagedFile(self.root / ".agents" / "skills" / "tsunagou-project" / "SKILL.md", skill),
        ] + host_files
        planned: list[tuple[Path, str, str]] = [
            self._plan_exact(item, refresh=refresh, force_managed=force_managed)
            for item in managed
        ]
        planned.append(
            self._plan_block(self.root / "AGENTS.md", agents_block, refresh=refresh, force_managed=force_managed)
        )
        planned.append(
            self._plan_block(self.root / ".gitignore", gitignore_block, refresh=refresh, force_managed=force_managed)
        )
        if host_config:
            config_path = self.root / ".codex/config.toml"
            config_plan = self._plan_block(
                config_path, host_config, refresh=refresh, force_managed=force_managed,
                start_marker="# TSUNAGOU:START", end_marker="# TSUNAGOU:END",
            )
            try:
                tomllib.loads(config_plan[1])
            except tomllib.TOMLDecodeError as exc:
                raise ProjectIntegrationError(f"host_config_conflict:{config_path}") from exc
            planned.append(config_plan)
        # All conflict checks happen before the first replacement. A user-file
        # conflict therefore cannot leave a partially materialized project.
        statuses: list[dict[str, str]] = []
        for path, content, status in planned:
            if status != "unchanged":
                _atomic_text(path, content)
            statuses.append({"path": str(path.relative_to(self.root)), "status": status})
        return {
            "status": "bootstrapped", "project_id": registry.project.project_id,
            "coordination_root": str(self.root), "source": source,
            "hosts": selected_hosts, "content_digest": content_digest,
            "files": statuses, "secrets_written": False,
        }

    def _plan_exact(self, item: _ManagedFile, *, refresh: bool, force_managed: bool) -> tuple[Path, str, str]:
        existing = _read(item.path)
        if existing is None:
            return item.path, item.content, "created"
        if existing == item.content:
            return item.path, existing, "unchanged"
        if not (refresh or force_managed) or "project-bootstrap-v" not in existing:
            raise ProjectIntegrationError(f"managed_file_conflict:{item.path}")
        return item.path, item.content, "updated"

    def _plan_block(
        self, path: Path, block: str, *, refresh: bool, force_managed: bool,
        start_marker: str = START_MARKER, end_marker: str = END_MARKER,
    ) -> tuple[Path, str, str]:
        existing = _read(path)
        if existing is not None and start_marker in existing and end_marker in existing:
            start = existing.find(start_marker)
            end = existing.find(end_marker, start)
            if end < start:
                raise ProjectIntegrationError(f"managed_marker_conflict:{path}")
            current = existing[start : end + len(end_marker)]
            if current != block and not (refresh or force_managed):
                raise ProjectIntegrationError(f"managed_file_conflict:{path}")
        updated, status = _replace_block(existing, block, path=path, start_marker=start_marker, end_marker=end_marker)
        return path, updated, status
